version: '3.9'

networks:
  local-server:
    driver: bridge

services:
  nginx:
    container_name: 'nginx-docker'
    image: 'nginx:mainline-alpine'
    volumes:
      - .templates:/etc/nginx/templates
    ports:
      - 8081:80
    environment:
      - NGINX_HOST=local.fr
      - NGINX_PORT=80
